QuanLyKho/Areas/Admin/Controllers/HomeAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QuanLyKho.Areas.Admin.Controllers
{
    public class HomeAdminController : Controller
    {
        //khóa
        [Authorize(Roles = "Admin")]
        // GET: Admin/HomeAdmin
        public ActionResult Index()
        {
            return View();
        }
    }
}

QuanLyKho/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Trang chủ", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">


                    <li>@Html.ActionLink("Giới Thiệu", "About", "Home")</li>
                    <li>@Html.ActionLink("Liên Hệ", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Tạo tài khoản", "Register", "Accounts", new { area = "" }, new { @class = "navbar-brand" })</li>
                    <li>@Html.ActionLink("Đăng nhập", "Login", "Accounts", new { area = "" }, new { @class = "navbar-brand" })</li>
                    <li>@Html.ActionLink("Đăng xuất", "Logout", "Accounts", new { area = "" }, new { @class = "navbar-brand" })</li>           
                    <li>@Html.ActionLink("Admin", "Index", "HomeAdmin", new { area = "Admin" }, new { @class = "navbar-brand" })</li>
                    <li>@Html.ActionLink("Client", "Index", "HomeClient", new { area = "Client" }, new { @class = "navbar-brand" })</li>

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Lập Trình Quản Lý</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>